name: Example Build & Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - v4
    tags:
      - v1
    paths:
      - 'website/**'
      - 'docs/**'
      - '.github/**'
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: npm script 🔧
        run: |
          npm install --registry=https://registry.npmjs.com
          npm run install:website
          npm run build:website
        env:
          CI: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/dist
          GIT_CONFIG_NAME: ${{ secrets.GIT_CONFIG_NAME}}
          GIT_CONFIG_EMAIL: ${{ secrets.GIT_CONFIG_EMAIL}}
